
sankey-beta

    Your Rankings,Go With the Flow,5
    Go With the Flow,Global Rankings,2

    Your Rankings,I Sat by the Ocean,3  
    I Sat by the Ocean,Global Rankings,7

    Your Rankings,In My Head,4
    In My Head,Global Rankings,9

    Your Rankings,3s and 7s,7
    3s and 7s,Global Rankings,6

    Your Rankings,Make It Wit Chu,10
    Make It Wit Chu,Global Rankings,4

    Your Rankings,Do It Again,17
    Do It Again,Global Rankings,12

    Your Rankings,Little Sister,19  
    Little Sister,Global Rankings,3

    %% Config
    %%{init: {"sankey": {"showValues": false}}}%%
